# permissions for end users to edit dynamicverticalpodautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dynamicverticalpodautoscaler-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dynamic-vertical-pod-autoscaler
    app.kubernetes.io/part-of: dynamic-vertical-pod-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: dynamicverticalpodautoscaler-editor-role
rules:
- apiGroups:
  - autoscaling.stackrox.io
  resources:
  - dynamicverticalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.stackrox.io
  resources:
  - dynamicverticalpodautoscalers/status
  verbs:
  - get
